version: "3.7"
services:
  cr:
    image: pwillie/chart-releaser:local
    entrypoint: []
    environment:
      - CR_TOKEN
    volumes:
      - .:/work
    working_dir: /work

  helm:
    image: alpine/helm:3.1.2
    entrypoint: []
    volumes:
      - .:/work
    working_dir: /work
