apiVersion: v1
appVersion: 0.1.1
version: 0.1.2
description: A Helm chart that deploys a mutating admission webhook that configures applications to request env vars from AWS SSM
name: ssm-secrets-webhook
maintainers:
- name: Peter Wilson
