apiVersion: v1
entries:
  ssm-secrets-webhook:
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2020-04-07T22:42:48.454944586Z"
    description: A Helm chart that deploys a mutating admission webhook that configures
      applications to request env vars from AWS SSM
    digest: 4a5c268fea5e17901e043f2e547777d8f7338f09272db772cf6ff27b277bb75e
    maintainers:
    - name: Peter Wilson
    name: ssm-secrets-webhook
    urls:
    - https://github.com/pwillie/pwillie.github.io/releases/download/ssm-secrets-webhook-0.1.0/ssm-secrets-webhook-0.1.0.tgz
    version: 0.1.0
generated: "2020-04-07T22:42:48.353442656Z"
