name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Package
      run: make package
    - name: Upload
      run: CR_TOKEN=${{ secrets.GITHUB_TOKEN }} make upload
    - name: Index
      run: CR_TOKEN=${{ secrets.GITHUB_TOKEN }} make index
