name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Package
      run: make package
    # - name: Upload
    #   run: CR_TOKEN=${{ secrets.GITHUB_TOKEN }} make upload
    - name: Index
      run: CR_TOKEN=${{ secrets.GITHUB_TOKEN }} make index
    - name: Debug
      run: cat charts/index.yaml
    - name: Commit index.yaml
      run: |
        git config --global user.name 'Github Action'
        git config --global user.email 'pwillie@users.noreply.github.com'
        git commit -am "Updated index.yaml"
        git push
